### ISSUE TITLE
stable branch - Updater does not ask for update confirmation

### ISSUE THREAD

**Issue by BotchedRPR** [Rift-Mods/launcher#4]
Raising this issue because I have - frankly no interest in continuing 1.x. 
The codebase needed an entire rewrite and the updater will be a whole new thing in 2.0. 
I'm looking for someone that could make the updater raise a form that shows the changelog for 2.0 and asks if you want to update or not.
This will be useful because 2.0 will break all of the 3 mods that existed for 1.0.

**Comment by stef-the** [comment]
https://github.com/Rift-Mods/launcher/pull/5
problem solved?

**Comment by BotchedRPR** [comment]
Fixed by #5
